import "./assset/globals.css";
import { UserContextProvider } from "./userContext/page";

export const metadata = {
  title: "cocovoit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserContextProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </UserContextProvider>
  );
}
